templates:

  - name: chrome
    browser_name: chrome
    capture_console_logs: false
    options:
      headless: false
      accept_insecure_certs: true
      unhandled_prompt_behaviour: "accept"
      exclude_switches:
        - "enable-automation"
        - "load-extension"
      arguments:
        - "--start-maximized"
        - "--no-sandbox"
        - "--remote-allow-origins=*"
